### ISSUE TITLE
Miracast support

### ISSUE THREAD

**Issue by R0Wi** [synt4x93/android_device_samsung_starlte#1]
Hi and thanks for this nice port for the Samsung S9. I recently upgraded from LineageOS 15 like described [here](https://forum.xda-developers.com/galaxy-s9/samsung-galaxy-s9--s9-cross-device-development/rom-t3945595) and everything works like expected. Except the fact that i'm not able to share my screen via miracast. After tapping on the "share screen" icon, a dialog appears but no devices were found. With another S9 and Samsung stock ROM i have no issues.

Is it possible to add support for miracast or am i just doing anything wrong?

**Comment by R0Wi** [comment]
Hey @synt4x93, any feedback please?

**Comment by Razuuu** [comment]
@R0Wi He's dumb :)

**Comment by synt4x93** [comment]
Lol did not see this, aosp Miracast support is shitty

**Comment by R0Wi** [comment]
The only thing i had in mind was mirroring my android phones screen to anotherdevice like a smart TV. But like you said on Android this is really painful, doesn't feel like 2021.
