### ISSUE TITLE
Secure boot disables itself.

### ISSUE THREAD

**Issue by citizenserious** [synt4x93/android_device_samsung_starlte#9]
After a few reboots the system deactivates secure boot somehow it just skips the secure boot pin screen. I then have to delete the pin and reinstate it to activate secure boot again. I had the exact same issue on the official 17.1 LOS for the S9 (starlte).
Everything else is working so smooth, thanks a lot, awesome work!

**Comment by synt4x93** [comment]
Very strange.. sorry didn't see this until now. I'll encrypt and try to reproduce this issue.

**Comment by citizenserious** [comment]
I really don't know why, but now it seems to keep secure boot enabled (shows the white code screen "To start Android, enter your PIN" before the actual boot every time now, tried it very very often now). I wouldn't have even noticed that issue I mentioned in the first place if Spotify would have worked correctly. I downloaded songs to the SD-Card, because spotify has a very bad code (I think) spotify downloads all songs over again after every restart when secure boot is disabled, the SD-Card gets mounted after the system starts, so spotify can't find the SD-Card in time and changes the storage back to internal. I activated secure boot and the issue with spotify was gone (for the moment), but then this "skipping" (didn't have to put in a code before the normal screen) problem appeared.
I can't even reproduce the "skipping" myself now. Please don't waste your time, I think this is a really deep bug.
As I mentioned I had the same issue when using the official Lineage 17.1, so I don't think there is anything you can do right away. I am very sorry if I wasted your time I just didn't know where else to mention this bug. I am closing this for now.  I will keep an eye on this though. Can you tell me where to mention such an issue in the future? I think here isn't the absolute right place, am I right?
P.S. Thanks a lot for the latest release (: works flawless.
